name:                haskell-net
version:             0.1.0.0
github:              "githubuser/deep-haskell"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/deep-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- hmatrix == 0.20.0.0
- singletons == 2.5.1
- random
- bytestring
- zlib
- binary
- servant == 0.16.2
- servant-server == 0.16.2
- warp == 3.3.5
- aeson == 1.4.6.0
- text
- wai-cors == 0.2.7
- http-types

default-extensions:
- BangPatterns
- DataKinds
- DeriveGeneric
- GADTs
- KindSignatures
- LambdaCase
- ScopedTypeVariables
- TypeOperators
- OverloadedStrings

library:
  source-dirs: src

executables:
  haskell-net-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-net
